package frc.robot.robot_container;

import com.ctre.phoenix6.CANBus;

import frc.robot.CanID;

public class CanIDConstants {
    private CanIDConstants() {}
        public record MotorID(CanID can, CANBus bus) {}

        // Drive CanIds are assigned in TunerConstants.java 
        // Swerve CanIds are auto-generated by Phoenix Tuner X.

        public class Intake {
            public static final MotorID INTAKE_MOTOR = new MotorID(new CanID((byte) 1), new CANBus(""));
        }
}
